### ISSUE TITLE
BandwidthOptimizer crashes onMediaPlayerEvent()

### ISSUE THREAD

**Issue by Voto** [SRGSSR/SRGMediaPlayer-Android#1]
NPE if you change the play status by pausing playback. Seems this crash happens if you have no network.

Lib Version: 1.2.84

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.net.NetworkInfo.getType()' on a null object reference
                                                     at ch.srg.mediaplayer.BandwidthOptimizer.onMediaPlayerEvent(SourceFile:33)
                                                     at ch.srg.mediaplayer.SRGMediaPlayerController.doPostEventInternal(SourceFile:1226)
                                                     at ch.srg.mediaplayer.SRGMediaPlayerController.access$1600(SourceFile:36)
                                                     at ch.srg.mediaplayer.SRGMediaPlayerController$8.run(SourceFile:1219)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by SebastienChauvin** [comment]
Ok thanks, will look at this.

**Comment by Voto** [comment]
Great thanks!
