### ISSUE TITLE
Exoplayer does not play invalid Apple stream

### ISSUE THREAD

**Issue by SebastienChauvin** [SRGSSR/SRGMediaPlayer-Android#4]
### New Issue Checklist

- [ ] Updated libraries to the latest version
- [ ] Read through the README of the project

### Context description

```
Playing new Apple bipbop basic
```

### Issue Description

```

The Apple stream is currently invalid:
https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

References:
https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/alternate_audio_aac_sinewave/prog_index.m3u8
Which currently returns an HTTP 302 with the following body:
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>919BA57013B81A85</RequestId><HostId>MPBoN33tFQIl5BZlXn8eSl/wWtIBqmRhzsPSiZW+v3c6JNwN98N+MYd8/I2PNHjGbL1w9jqsgU0=</HostId></Error>```

#### Steps to reproduce the behaviour

```
Play the aforementioned video
```

##### Complete stacktrace output

```
                                                                          com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
                                                                              at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:119)
                                                                              at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:43)
                                                                              at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:115)
                                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
```


Will need to create an exoplayer bug

**Comment by SebastienChauvin** [comment]
Not important
